// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFDZ_Vwc6WPJaCwhyGjY2mrW-Wbxlo4dc',
    appId: '1:1034498336374:web:36e0586f8dd34f3357a157',
    messagingSenderId: '1034498336374',
    projectId: 'chatter-6f294',
    authDomain: 'chatter-6f294.firebaseapp.com',
    storageBucket: 'chatter-6f294.appspot.com',
    measurementId: 'G-4HNWQ6L0Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdM71Bk3IKhYYN0QagZLGWfC4ZvIc793g',
    appId: '1:1034498336374:android:9adc9a44abdb267357a157',
    messagingSenderId: '1034498336374',
    projectId: 'chatter-6f294',
    storageBucket: 'chatter-6f294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHIARgSeUUHhiFhTJWcgeivp--9MvrWPQ',
    appId: '1:1034498336374:ios:3af22aebcffe8c3b57a157',
    messagingSenderId: '1034498336374',
    projectId: 'chatter-6f294',
    storageBucket: 'chatter-6f294.appspot.com',
    iosBundleId: 'com.example.charterer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHIARgSeUUHhiFhTJWcgeivp--9MvrWPQ',
    appId: '1:1034498336374:ios:3af22aebcffe8c3b57a157',
    messagingSenderId: '1034498336374',
    projectId: 'chatter-6f294',
    storageBucket: 'chatter-6f294.appspot.com',
    iosBundleId: 'com.example.charterer',
  );
}
